# Generated by Django 5.2.5 on 2025-12-16 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_carga', models.CharField(choices=[('FACTOR', 'Carga por Factor'), ('MONTO', 'Carga por Monto')], max_length=10)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.CharField(choices=[('Acciones', 'Acciones'), ('Fondos de Inversión', 'Fondos de Inversión'), ('Bonos', 'Bonos'), ('Derivados', 'Derivados'), ('Otros', 'Otros')], default='Acciones', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=250)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('secuencia_evento', models.PositiveIntegerField(default=1)),
                ('dividendo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_historico', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('factor_actualizacion', models.DecimalField(decimal_places=8, default=1, max_digits=10)),
                ('anio', models.PositiveIntegerField(default=2025, verbose_name='Año')),
                ('isfut', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MontoCorredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EJERCICIO', models.CharField(blank=True, max_length=10, null=True)),
                ('MERCADO', models.CharField(blank=True, max_length=10, null=True)),
                ('NEMO', models.CharField(blank=True, max_length=100, null=True)),
                ('FEC_PAGO', models.CharField(blank=True, max_length=20, null=True)),
                ('SEC_EVE', models.CharField(blank=True, max_length=50, null=True)),
                ('DESCRIPCION', models.CharField(blank=True, max_length=255, null=True)),
                ('F8', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('F9', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('F10', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('F11', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('F12', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('F13', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Sistema.archivocargado')),
            ],
        ),
        migrations.CreateModel(
            name='CambioRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('tipo_cambio', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('ELIMINACION', 'Eliminación')], max_length=50)),
                ('detalle_registro', models.TextField()),
                ('calificacion_modificada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sistema.calificaciontributaria', verbose_name='Calificación Tributaria modificada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='instrumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Sistema.instrumento'),
        ),
        migrations.CreateModel(
            name='logAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('tipo_accion', models.CharField(max_length=20)),
                ('direccion_ip', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('success', 'Éxito'), ('danger', 'Error'), ('warning', 'Advertencia'), ('info', 'Información')], max_length=20)),
                ('mensaje', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FactorTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='Sistema.calificaciontributaria')),
            ],
            options={
                'unique_together': {('calificacion', 'numero')},
            },
        ),
    ]
